const data = {}

const OPEN = 1
const JUNGLE = 2
const MIXED = 3
const MOUNTAIN = 4
const ATOLL = 5

data.cards = [
    {
        "num": 1,
        "faction": "ap",
        "ops": 2,
        "oc": 2,
        "ec": 4,
        "remove": false,
        "intelligence": "surprise",
        "name": "Tarzan",
    },
    {
        "num": 2,
        "faction": "ap",
        "ops": 2,
        "oc": 2,
        "ec": 0,
        "remove": true,
        "name": "Sextant",
    },
    {
        "num": 3,
        "faction": "ap",
        "ops": 3,
        "oc": 3,
        "ec": 5,
        "remove": false,
        "name": "Dexterity",
    },
    {
        "num": 4,
        "faction": "ap",
        "ops": 2,
        "oc": 2,
        "ec": 0,
        "remove": true,
        "name": "WIE",
    },
    {
        "num": 5,
        "faction": "ap",
        "ops": 2,
        "oc": 2,
        "ec": 0,
        "remove": true,
        "name": "WIE",
    },
    {
        "num": 6,
        "faction": "ap",
        "ops": 1,
        "oc": 1,
        "ec": 0,
        "remove": false,
        "name": "JP Dispute",
    },
    {
        "num": 7,
        "faction": "ap",
        "ops": 2,
        "oc": 2,
        "ec": 0,
        "remove": false,
        "name": "Squarepeg",
    },
    {
        "num": 1,
        "faction": "jp",
        "ops": 2,
        "oc": 4,
        "ec": 0,
        "remove": true,
        "name": "Weather",
    },
    {
        "num": 2,
        "faction": "jp",
        "ops": 2,
        "oc": 4,
        "ec": 6,
        "remove": false,
        "name": "RE",
    },
    {
        "num": 3,
        "faction": "jp",
        "ops": 1,
        "oc": 3,
        "ec": 0,
        "remove": false,
        "name": "Submarine",
    },
    {
        "num": 4,
        "faction": "jp",
        "ops": 3,
        "oc": 5,
        "ec": 7,
        "remove": false,
        "name": "KA",
    },
    {
        "num": 5,
        "faction": "jp",
        "ops": 2,
        "oc": 4,
        "ec": 0,
        "remove": true,
        "name": "Kai-shek",
    },
    {
        "num": 6,
        "faction": "jp",
        "ops": 1,
        "oc": 3,
        "ec": 0,
        "remove": false,
        "name": "Submarine",
    },
    {
        "num": 7,
        "faction": "jp",
        "ops": 3,
        "oc": 5,
        "ec": 7,
        "remove": false,
        "name": "Tokyo Express",
    },
]

data.pieces = [
    {
        "faction": "jp",
        "name": "Army 1",
        "class": "ground",
        "size": 4,
        "counter": "army_jp",
        "cf": 18,
        "lf": 12,
        "rcf": 9,
        "rlf": 12,
        "rptype": "jp_ground",
        "start": 3706
    },
    {
        "faction": "jp",
        "name": "Air 1",
        "class": "air",
        "counter": "air_jp",
        "cf": 20,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 10,
        "rlf": 10,
        "start": 3706
    },
    {
        "faction": "jp",
        "name": "Air 2",
        "class": "air",
        "counter": "air_jp",
        "cf": 20,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 10,
        "rlf": 10,
        "start": 3706
    },
    {
        "faction": "jp",
        "name": "Ship 1",
        "class": "naval",
        "type": "cv",
        "counter": "navy_jp",
        "cf": 14,
        "lf": 12,
        "br": 3,
        "rcf": 10,
        "rlf": 12,
        "rptype": "navy_jp",
        "start": 3706
    },
    {
        "faction": "jp",
        "name": "Combined HQ",
        "class": "hq",
        "counter": "hq_jp",
        "cr": 13,
        "cm": 3,
        "start": 3706
    },
    {
        "faction": "ap",
        "name": "Army 1",
        "class": "ground",
        "size": 4,
        "counter": "army_us",
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rlf": 12,
        "rptype": "ap_ground",
        "start": 2909
    },
    {
        "faction": "ap",
        "name": "Army 2",
        "class": "ground",
        "size": 4,
        "counter": "army_us",
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rlf": 12,
        "rptype": "ap_ground",
        "start": 3009
    },
    {
        "faction": "ap",
        "name": "Army 3",
        "class": "ground",
        "size": 4,
        "counter": "army_us",
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rlf": 12,
        "rptype": "ap_ground",
        "start": 3009
    },
    {
        "faction": "ap",
        "name": "Army 4",
        "class": "ground",
        "size": 4,
        "counter": "army_us",
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rlf": 12,
        "rptype": "ap_ground",
        "start": 2709
    },
    {
        "faction": "ap",
        "name": "Army 5",
        "class": "ground",
        "size": 4,
        "counter": "army_us",
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rlf": 12,
        "rptype": "ap_ground",
        "start": 3009
    },
    {
        "faction": "ap",
        "name": "Air 1",
        "class": "air",
        "type": "sra",
        "counter": "air_us",
        "cf": 6,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
        "rlf": 10,
        "rptype": "air_ap",
        "start": 2909
    },
    {
        "faction": "ap",
        "name": "Air 2",
        "class": "air",
        "type": "sra",
        "counter": "air_us",
        "cf": 6,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
        "rlf": 10,
        "rptype": "air_ap",
        "start": 2909
    },
    {
        "faction": "ap",
        "name": "Ship 1",
        "class": "naval",
        "type": "cv",
        "counter": "navy_us",
        "cf": 22,
        "lf": 12,
        "br": 2,
        "rcf": 11,
        "rlf": 12,
        "rptype": "navy_ap",
        "start": 2909
    },
    {
        "faction": "ap",
        "name": "Cp HQ",
        "class": "hq",
        "counter": "hq_us",
        "cr": 25,
        "cm": 3,
        "start": 2909
    },
]

//Hex sides
//N,NE,SE,S,SW,NW
//WATER_: 1, GROUND: 2, ROAD: 4, UNPASSABLE: 8
data.hex = [
    {id: 1005, name: "Maldive Is.", airfield: true, port: true, terrain: OPEN, island: true},
    {id: 1307, name: "Colombo", airfield: true, port: true, terrain: MIXED, edges: [1, 1, 1, 3, 3, 1]},
    {id: 1308, name: "Trincomalee", airfield: true, port: true, terrain: MIXED, edges: [3, 1, 1, 1, 1, 3]},
    {id: 1208, terrain: MIXED, edges: [1, 3, 3, 1, 1, 1]},
    {id: 1206, region: "India", terrain: OPEN, edges: [1, 8, 3, 1, 1, 1]},
    {id: 1306, region: "India", terrain: OPEN, edges: [8, 3, 1, 1, 1, 3]},
    {id: 1406, name: "Madras", region: "India", airfield: true, port: true, terrain: OPEN, edges: [8, 4, 1, 1, 3, 8]},
    {id: 1505, region: "India", terrain: OPEN, edges: [8, 8, 5, 1, 4, 8]},
    {id: 1606, region: "India", terrain: OPEN, edges: [8, 5, 1, 1, 1, 5]},
    {id: 1705, region: "India", terrain: OPEN, edges: [8, 4, 1, 1, 5, 8]},
    {id: 1805, name: "Calcutta", region: "India", airfield: true, port: true, terrain: OPEN, edges: [8, 8, 5, 1, 4, 8]},
    {id: 1709, name: "Little Andaman", terrain: OPEN, island: true},
    {id: 1809, name: "Andaman", terrain: OPEN, island: true},
    {id: 1710, name: "Nicobar", terrain: OPEN, island: true},
    {id: 1905, name: "Dacca", region: "NIndia", airfield: true, port: true, terrain: OPEN, edges: [8, 4, 3, 1, 1, 5]},
    {id: 2005, name: "Dimasur", region: "NIndia", terrain: OPEN, edges: [2, 4, 2, 2, 4, 8]},
    {id: 2104, name: "Jarhat", region: "NIndia", airfield: true, terrain: OPEN, edges: [2, 2, 4, 4, 4, 2]},
    {id: 2105, name: "Imphal", region: "NIndia", terrain: MIXED, edges: [4, 2, 2, 4, 2, 2]},
    {id: 2205, name: "Ledo", region: "NIndia", terrain: MIXED, edges: [2, 2, 4, 2, 2, 4]},
    {id: 2004, terrain: MOUNTAIN,},
    {id: 2103, terrain: MOUNTAIN,},
    {id: 2204, terrain: MOUNTAIN,},
    {id: 2303, terrain: MOUNTAIN,},
    {id: 2304, terrain: MOUNTAIN,},
    {id: 2405, terrain: MOUNTAIN,},
    {id: 2006, name: "Akyab", region: "Burma", airfield: true, terrain: JUNGLE, edges: [2, 2, 2, 2, 1, 3]},
    {id: 2007, region: "Burma", terrain: JUNGLE, edges: [2, 4, 2, 4, 1, 1]},
    {
        id: 2008,
        name: "Rangoon",
        region: "Burma",
        airfield: true,
        port: true,
        resource: true,
        terrain: JUNGLE,
        edges: [4, 4, 4, 1, 8, 8]
    },
    {id: 2106, name: "Mandalay", region: "Burma", airfield: true, terrain: JUNGLE, edges: [4, 4, 2, 4, 4, 2]},
    {id: 2107, region: "Burma", terrain: JUNGLE, edges: [4, 2, 2, 2, 4, 2]},
    {id: 2108, region: "Burma", terrain: MIXED, edges: [2, 2, 2, 4, 1, 4]},
    {id: 2206, name: "Lashio", airfield: true, region: "Burma", terrain: MIXED, edges: [2, 4, 4, 2, 4, 2]},
    {id: 2305, name: "Myitkyina", airfield: true, region: "Burma", terrain: MIXED, edges: [2, 2, 2, 2, 4, 4]},
    {id: 2207, region: "Burma", terrain: JUNGLE},
    {id: 2407, name: "Kunming", region: "IChina", terrain: MIXED, edges: [2, 2, 2, 2, 2, 4]},
    {id: 2306, region: "IChina", terrain: MIXED, edges: [2, 2, 4, 2, 2, 4]},
    {id: 2406, region: "IChina", terrain: MIXED},
    {id: 2506, region: "IChina", terrain: MIXED},
    {id: 2507, region: "IChina", terrain: MIXED},
    {id: 2408, region: "IChina", terrain: MIXED},
    {id: 2307, region: "IChina", terrain: MIXED},
    {id: 2109, region: "Siam", terrain: JUNGLE, edges: [5, 2, 2, 2, 5, 1]},
    {id: 2110, name: "Udorn", region: "Siam", terrain: OPEN, edges: [2, 2, 2, 2, 4, 2]},
    {id: 2209, region: "Siam", terrain: MIXED},
    {id: 2010, region: "Siam", terrain: MIXED, edges: [1, 5, 4, 2, 1, 1]},
    {id: 2110, name: "Bangkok", region: "Siam", airfield: true, port: true, terrain: MIXED, edges: [2, 4, 4, 3, 5, 4]},
    {id: 2011, region: "Siam", terrain: JUNGLE, edges: [2, 5, 1, 5, 2, 8]},
    {id: 1911, region: "Siam", terrain: JUNGLE, edges: [1, 2, 2, 1, 1, 1]},
    {id: 2012, name: "Singora", region: "Malaya", airfield: true, terrain: OPEN, edges: [5, 1, 5, 2, 4, 2]},
    {id: 2112, name: "Kota Bhary", region: "Malaya", airfield: true, terrain: OPEN, edges: [1, 1, 1, 3, 4, 5]},
    {id: 1912, name: "Jitra", region: "Malaya", airfield: true, terrain: MIXED, edges: [1, 4, 2, 5, 1, 1]},
    {id: 2013, region: "Malaya", terrain: MOUNTAIN, edges: [2, 4, 2, 4, 2, 2]},
    {id: 2113, region: "Malaya", terrain: MIXED, edges: [3, 1, 1, 1, 3, 2]},
    {id: 1913, name: "Kuala Lumpur", region: "Malaya", airfield: true, terrain: MIXED, edges: [5, 2, 4, 1, 1, 1]},
    {
        id: 2014,
        name: "Kuantan",
        region: "Malaya",
        airfield: true,
        resource: true,
        terrain: MIXED,
        edges: [4, 3, 1, 4, 8, 4]
    },
    {
        id: 2015,
        name: "Singapore",
        region: "Malaya",
        airfield: true,
        port: true,
        terrain: MIXED,
        edges: [4, 1, 1, 1, 1, 1]
    },
    {id: 2111, region: "Indochina", airfield: true, terrain: MIXED, edges: [3, 2, 2, 1, 1, 1]},
    {id: 2211, name: "Phom Penh", region: "Indochina", airfield: true, terrain: MIXED, edges: [2, 2, 2, 4, 2, 4]},
    {
        id: 2212,
        name: "Saigon",
        region: "Indochina",
        airfield: true,
        port: true,
        terrain: MIXED,
        edges: [4, 4, 3, 1, 1, 2]
    },
    {
        id: 2311,
        name: "Cam Ranh",
        region: "Indochina",
        airfield: true,
        port: true,
        terrain: MIXED,
        edges: [2, 5, 1, 3, 4, 2]
    },
    {id: 2312, region: "Indochina", terrain: MIXED, edges: [3, 1, 1, 1, 3, 1]},
    {id: 2411, region: "Indochina", terrain: MIXED, edges: [1, 1, 1, 1, 5, 4]},
    {id: 2310, region: "Indochina", terrain: MIXED, edges: [2, 4, 4, 2, 2, 2]},
    {id: 2410, name: "Hue", region: "Indochina", terrain: MIXED, edges: [1, 1, 1, 1, 4, 5]},
    {id: 2309, region: "Indochina", terrain: MIXED, edges: [2, 5, 5, 2, 2, 2]},
    {id: 2308, region: "Indochina", terrain: MIXED},
    {id: 2208, region: "Indochina", terrain: MIXED},
    {
        id: 2409,
        name: "Hanoi",
        airfield: true,
        port: true,
        region: "Indochina",
        terrain: OPEN,
        edges: [2, 5, 1, 1, 5, 2]
    },
    {id: 2508, name: "Yungning", airfield: true, port: true, region: "China", terrain: OPEN, edges: [2, 8, 2, 1, 5, 2]},
    {id: 2509, name: "Hainan", port: true, region: "China", terrain: OPEN, edges: [1, 1, 8, 8, 1, 1]},
    {id: 2609, name: "Canton", airfield: true, port: true, region: "China", terrain: MIXED, edges: [8, 4, 1, 1, 1, 2]},
    {id: 2708, region: "China", terrain: MIXED, edges: [8, 8, 3, 5, 4, 8]},
    {
        id: 2709,
        name: "Hong Kong",
        airfield: true,
        port: true,
        region: "Hong Kong",
        terrain: MIXED,
        edges: [5, 1, 1, 1, 1, 1]
    },
    {id: 2809, name: "Swatow", airfield: true, port: true, region: "China", terrain: MIXED, edges: [8, 3, 1, 1, 1, 3]},
    {id: 2908, name: "Wenchow", airfield: true, port: true, region: "China", terrain: OPEN, edges: [8, 3, 1, 1, 3, 8]},
    {
        id: 2909,
        name: "Tainan",
        airfield: true,
        port: true,
        region: "Formosa",
        terrain: MIXED,
        edges: [1, 3, 1, 1, 1, 1]
    },
    {id: 3009, name: "Taihoku", airfield: true, region: "Formosa", terrain: MIXED, edges: [1, 1, 1, 1, 3, 1]},
    {id: 3008, region: "China", terrain: MIXED, edges: [3, 1, 1, 1, 3, 8]},
    {id: 3007, name: "Shanghai", airfield: true, port: true, region: "China", terrain: OPEN, edges: [2, 3, 1, 3, 8, 8]},
    {id: 3106, region: "China", terrain: OPEN, edges: [1, 1, 1, 1, 3, 3]},
    {id: 3006, region: "China", terrain: OPEN, edges: [2, 3, 3, 2, 8, 8]},
    {
        id: 3105,
        name: "Tsingtao",
        airfield: true,
        port: true,
        region: "China",
        terrain: MIXED,
        edges: [1, 1, 1, 1, 3, 4]
    },
    {id: 3005, name: "Tientsin", airfield: true, region: "China", terrain: OPEN, edges: [4, 8, 4, 2, 8, 8]},
    {id: 3004, name: "Peiping", airfield: true, region: "China", terrain: OPEN, edges: [8, 4, 8, 4, 8, 8]},
    {id: 3103, region: "China", terrain: MIXED, edges: [8, 4, 2, 8, 4, 8]},
    {
        id: 3104,
        name: "Port Arthur",
        airfield: true,
        port: true,
        region: "China",
        terrain: OPEN,
        edges: [8, 4, 1, 1, 8, 8]
    },
    {id: 3203, region: "Manchuria", terrain: OPEN, edges: [8, 4, 2, 2, 4, 8]},
    {id: 3204, region: "Manchuria", terrain: OPEN, edges: [2, 4, 2, 8, 4, 2]},
    {id: 3402, region: "Manchuria", terrain: MIXED, edges: [8, 8, 8, 2, 2, 8]},
    {id: 3403, region: "Manchuria", terrain: MOUNTAIN, edges: [2, 8, 8, 2, 2, 2]},
    {id: 3404, region: "Manchuria", terrain: MOUNTAIN, edges: [2, 1, 1, 1, 3, 2]},
    {
        id: 3302,
        name: "Harbin",
        airfield: true,
        resource: true,
        region: "Manchuria",
        terrain: OPEN,
        edges: [8, 2, 2, 2, 4, 8]
    },
    {
        id: 3303,
        name: "Mukden",
        airfield: true,
        resource: true,
        region: "Manchuria",
        terrain: OPEN,
        edges: [4, 2, 2, 4, 4, 2]
    },
    {id: 3304, region: "Korea", terrain: MOUNTAIN, edges: [4, 3, 1, 4, 2, 2]},
    {id: 3205, region: "Korea", terrain: MIXED, edges: [8, 2, 3, 1, 1, 1]},
    {
        id: 3305,
        name: "Seoul",
        airfield: true,
        port: true,
        resource: true,
        region: "Korea",
        terrain: MIXED,
        edges: [4, 8, 8, 4, 3, 3]
    },
    {id: 3306, name: "Pusan", airfield: true, port: true, region: "Korea", terrain: MIXED, edges: [4, 1, 8, 1, 1, 3]},
    {id: 3206, region: "Korea", terrain: MIXED, edges: [1, 3, 3, 1, 1, 1]},
    {id: 3209, name: "Okinawa", airfield: true, port: true, island: true, region: "JMandates", terrain: MIXED},
    {id: 3308, name: "Shima", island: true, region: "JMandates", terrain: MIXED},
    {id: 3309, name: "Rasa", island: true, region: "JMandates", terrain: MIXED},
    {id: 3708, name: "Bonin", island: true, region: "JMandates", terrain: MIXED},
    {id: 3709, name: "Iwo Jima", airfield: true, island: true, region: "JMandates", terrain: MIXED},
    {id: 4110, name: "Marcus", airfield: true, island: true, region: "JMandates", terrain: OPEN},
    {id: 3812, name: "Asuncion", island: true, region: "JMandates", terrain: MIXED},
    {id: 3813, name: "Saipan", airfield: true, port: true, island: true, region: "JMandates", terrain: MIXED},
    {id: 3416, name: "Palau", airfield: true, port: true, island: true, region: "JMandates", terrain: MIXED},
    {id: 3515, name: "Yap", airfield: true, island: true, region: "JMandates", terrain: OPEN},
    {id: 3615, name: "Ulithi", airfield: true, port: true, region: "JMandates", terrain: ATOLL},
    {id: 3716, name: "Woleai", region: "Caroline", terrain: ATOLL},
    {id: 3816, name: "Faraulep", region: "Caroline", terrain: ATOLL},
    {id: 3817, name: "Ifalik", region: "Caroline", terrain: ATOLL},
    {id: 3916, name: "Pulap", region: "Caroline", terrain: ATOLL},
    {id: 4016, name: "Hall", region: "Caroline", terrain: ATOLL},
    {id: 4017, name: "Truk", airfield: true, port: true, region: "Caroline", terrain: ATOLL},
    {id: 4117, name: "Nomoi", region: "Caroline", terrain: ATOLL},
    {id: 4316, name: "Ponape", airfield: true, island: true, region: "Marshall", terrain: OPEN},
    {id: 4517, name: "Kusaie", airfield: true, island: true, region: "Marshall", terrain: OPEN},
    {id: 4713, name: "Taongi", region: "Marshall", terrain: OPEN},
    {id: 4415, name: "Eniwetok",airfield: true, port: true, region: "Marshall", terrain: ATOLL},
    {id: 4715, name: "Kwajalein",airfield: true, port: true, region: "Marshall", terrain: ATOLL},
    {id: 4615, name: "Rongelap", region: "Marshall", terrain: ATOLL},
    {id: 4616, name: "Ujae", region: "Marshall", terrain: ATOLL},
    {id: 4716, name: "Namu",airfield: true, region: "Marshall", terrain: ATOLL},
    {id: 4815, name: "Wotje",airfield: true, region: "Marshall", terrain: ATOLL},
    {id: 4816, name: "Maloelap",airfield: true, region: "Marshall", terrain: ATOLL},
    {id: 4817, name: "Jaluit",airfield: true, region: "Marshall", terrain: ATOLL},
    {id: 4916, name: "Mili",airfield: true, region: "Marshall", terrain: ATOLL},
    {id: 3800, region: "Sakhalin", terrain: MIXED, edges: [8, 8, 1, 3, 1, 8]},
    {id: 3801, region: "Sakhalin", terrain: MIXED, edges: [3, 8, 8, 3, 1, 1]},
    {id: 3802, region: "Sakhalin", terrain: MIXED, edges: [3, 8, 8, 3, 1, 1]},
    {id: 3803, region: "Sakhalin", terrain: MIXED, edges: [3, 1, 1, 1, 1, 1]},
    {id: 3703, region: "Japan", terrain: MIXED, edges: [1, 1, 3, 3, 1, 1]},
    {id: 3804, region: "Japan", terrain: MIXED, edges: [1, 1, 1, 3, 2, 3]},
    {id: 3704, name:"Hakodate",airfield: true,port: true,region: "Japan", terrain: MIXED, edges: [3, 2, 1, 1, 1, 1]},
    {id: 3705, name:"Ominato",airfield: true,port: true,region: "Japan", terrain: MIXED, edges: [1, 1, 1, 3, 2, 8]},
    {id: 3706, name:"Tokyo",airfield: true,port: true,region: "Japan", terrain: OPEN, edges: [3, 1, 1, 1, 3, 2]},
    {id: 3606,region: "Japan", terrain: MIXED, edges: [1, 2, 2, 2, 3, 1]},
    {id: 3607, name:"Nagoya",airfield: true,port: true,region: "Japan", terrain: MIXED, edges: [2, 3, 1, 1, 1, 2]},
    {id: 3506, name:"Kyoto",airfield: true,region: "Japan", terrain: MIXED, edges: [1, 3, 2, 2, 2, 1]},
    {id: 3507, name:"Osaka",airfield: true,port:true,region: "Japan", terrain: MIXED, edges: [2, 1, 1, 1, 1, 1]},
    {id: 3407, name:"Kure",airfield: true,port:true,region: "Japan", terrain: MIXED, edges: [8, 2, 1, 1, 1, 8]},
    {id: 3307, name:"Kynshu",airfield: true,port:true,region: "Japan", terrain: MIXED, edges: [1, 1, 8, 1, 1, 1]},
    {id: 2911, airfield: true,region: "Philippines", terrain: MIXED, edges: [1, 1, 1, 3, 3, 1]},
    {id: 2811, airfield: true,region: "Philippines", terrain: OPEN, edges: [1, 3, 2, 3, 1, 1]},
    {id: 2912,region: "Philippines", terrain: MIXED, edges: [3, 1, 1, 2, 2, 2]},
    {id: 2913,region: "Philippines", terrain: MIXED, edges: [2, 1, 8, 1, 8, 1]},
    {id: 2814,name:"Panay",region: "Philippines", terrain: MIXED, edges: [1, 8, 1, 1, 1, 1]},
    {id: 2914,name:"Cebu",region: "Philippines", terrain: MIXED, edges: [1, 8, 1, 8, 1, 1]},
    {id: 2713,region: "Philippines", terrain: MIXED, edges: [1, 1, 1, 2, 1, 1]},
    {id: 2714,region: "Philippines", terrain: MIXED, edges: [2, 1, 1, 1, 1, 1]},
    {id: 3015,region: "Philippines", terrain: MIXED, edges: [1, 1, 1, 3, 2, 1]},
    {id: 3016,region: "Philippines", terrain: MIXED, edges: [3, 1, 1, 1, 1, 3]},
    {id: 2815,region: "Philippines", terrain: MIXED, edges: [1, 1, 2, 1, 1, 1]},
    {id: 2813,name:"Manila",airfield: true,port: true,resource: true,region: "Philippines", terrain: MIXED, edges: [3, 2, 1, 1, 1, 1]},
    {id: 3014,name:"Layte",airfield: true,port: true,region: "Philippines", terrain: MIXED, edges: [1, 1, 1, 1, 8, 8]},
    {id: 2915,name:"Davao",airfield: true,port: true,region: "Philippines", terrain: MIXED, edges: [8, 2, 3, 1, 8, 2]},
    {id: 2715,name:"Jolo",airfield: true,port: true,region: "Philippines", terrain: OPEN, island: true},
]

if (typeof module !== 'undefined') module.exports = data
